FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# JobPortal

Job Portal is an API exposing REST end points to manage a Job Portal

## Jobs [/jobs]

### List All Jobs [GET]

End point to fetch all the jobs listed so far

+ Response 200 (application/json)

        [{"jId":1,"category":
        {"categoryName":"Developer","cid":1},"postedBy":{"emailId":"sai.chandra@practo.com","eid":1},"recruitId":null,"description":"Need a developer","closed":false}]

### Create a new Job [POST]

End point to create a new job listing. Category Id, Admin Id and description for the job are expected

+ Request (application/json)

        {"category_id":1,"postedBy":1,"description":"Need a developer"}

+ Response 201 (application/json)

    + Headers

            

    + Body

            {
                "responseCode": 101,
                "message": "Job added succesfully",
            }

## Job Applications [/jobs/{jobId}/applications]
            
### List All Job Applications [GET]

End point that lists all the applications received for a job so far.

+ Parameters
    + jobId - id of a Job listing

+ Response 200 (application/json)

        {"jId":1}
        
### New Job application [POST]    
End point to add a new job application

+ Request (application/json)

        {"jId":1,"appliedBy":1}

+ Response 201 (application/json)

    + Headers

            

    + Body

            {
                "responseCode": 102,
                "message": "Job application added succesfully",
            }
            
## Job Application [/applications/{appId}]            
            
### Delete Job application [DELETE]    
End point to delete an existing job application

+ Parameters
    + appId - applicationId

+ Request (application/json)

        {"jId":1,"appliedBy":1}

+ Response 201 (application/json)

    + Headers

            

    + Body

            {
                "responseCode": 102,
                "message": "Job application added succesfully",
            }
            
## Categories [/categories]

### Get all Job Categories [GET]    
End point to fetch all the Job categories

+ Response 200 (application/json)

        [{"categoryName":"Administrator","cid":4}]