package com.practo.sai.jobportal.entities;
// Generated Oct 17, 2016 1:36:19 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "job_portal", uniqueConstraints = @UniqueConstraint(columnNames = "category_name"))
public class Category implements java.io.Serializable {

	private Integer CId;
	private String categoryName;
	// private Set<Job> jobs = new HashSet<Job>(0);

	public Category() {
	}

	public Category(String categoryName) {
		this.categoryName = categoryName;
	}

	// public Category(String categoryName, Set<Job> jobs) {
	// this.categoryName = categoryName;
	// this.jobs = jobs;
	// }

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "c_id", unique = true, nullable = false)
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	@Column(name = "category_name", unique = true, nullable = false)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	// @OneToMany(fetch = FetchType.EAGER, mappedBy = "category")
	// public Set<Job> getJobs() {
	// return this.jobs;
	// }

	// public void setJobs(Set<Job> jobs) {
	// this.jobs = jobs;
	// }

}
