package com.practo.sai.jobportal.entities;
// Generated Oct 17, 2016 1:36:19 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApplication generated by hbm2java
 */
@Entity
@Table(name = "job_application", catalog = "job_portal")
public class JobApplication implements java.io.Serializable {

	private Integer JAppId;
	private Employee employee;
	private Job job;
	private Date appliedOn;

	public JobApplication() {
	}

	public JobApplication(Employee employee, Job job) {
		this.employee = employee;
		this.job = job;
	}

	public JobApplication(Employee employee, Job job, Date appliedOn) {
		this.employee = employee;
		this.job = job;
		this.appliedOn = appliedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "j_app_id", unique = true, nullable = false)
	public Integer getJAppId() {
		return this.JAppId;
	}

	public void setJAppId(Integer JAppId) {
		this.JAppId = JAppId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "applied_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "job_id", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "applied_on", length = 19)
	public Date getAppliedOn() {
		return this.appliedOn;
	}

	public void setAppliedOn(Date appliedOn) {
		this.appliedOn = appliedOn;
	}

}
