package com.practo.sai.jobportal.entities;
// Generated Oct 17, 2016 1:36:19 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "job_portal")
public class UserRole implements java.io.Serializable {

  private Integer id;
  private Employee employee;
  private Role role;

  public UserRole() {}

  public UserRole(Employee employee, Role role) {
    this.employee = employee;
    this.role = role;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)

  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "e_id", nullable = false)
  public Employee getEmployee() {
    return this.employee;
  }

  public void setEmployee(Employee employee) {
    this.employee = employee;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "r_id", nullable = false)
  public Role getRole() {
    return this.role;
  }

  public void setRole(Role role) {
    this.role = role;
  }

}
